SYSCALL_SPECS = {
    # === Memory Management ===
    "mmap": ["addr", "size", "mmap_prot", "mmap_flags", "fd", "offset"],
    "munmap": ["addr", "size"],
    "mprotect": ["addr", "size", "mmap_prot"],
    "mremap": ["addr", "size", "size", "flags", "addr"],
    "msync": ["addr", "size", "flags"],
    "madvise": ["addr", "size", "random_int"],
    "mincore": ["addr", "size", "addr"],
    "mlock": ["addr", "size"],
    "munlock": ["addr", "size"],
    "mlockall": ["flags"],
    "munlockall": [],
    "brk": ["addr"],
    "memfd_create": ["addr", "flags"],
    "membarrier": ["random_int", "flags"],
    
    # === File Operations ===
    "open": ["path", "open_flags", "mode"],
    "openat": ["fd", "path", "open_flags", "mode"],
    "close": ["valid_fd"],
    "read": ["valid_fd", "addr", "size"],
    "write": ["valid_fd", "addr", "size"],
    "readv": ["valid_fd", "addr", "random_int"],
    "writev": ["valid_fd", "addr", "random_int"],
    "pread64": ["valid_fd", "addr", "size", "offset"],
    "pwrite64": ["valid_fd", "addr", "size", "offset"],
    "preadv": ["valid_fd", "addr", "random_int", "offset"],
    "pwritev": ["valid_fd", "addr", "random_int", "offset"],
    "lseek": ["valid_fd", "offset", "random_int"],
    "dup": ["valid_fd"],
    "dup2": ["valid_fd", "fd"],
    "dup3": ["valid_fd", "fd", "flags"],
    "pipe": ["addr"],
    "pipe2": ["addr", "flags"],
    
    # === File Metadata ===
    "stat": ["path", "addr"],
    "fstat": ["valid_fd", "addr"],
    "lstat": ["path", "addr"],
    "fstatat": ["fd", "path", "addr", "flags"],
    "statx": ["fd", "path", "flags", "random_int", "addr"],
    "access": ["path", "flags"],
    "faccessat": ["fd", "path", "flags"],
    "faccessat2": ["fd", "path", "flags", "flags"],
    
    # === File Operations (Advanced) ===
    "fcntl": ["valid_fd", "fcntl_cmd", "random_int"],
    "ioctl": ["valid_fd", "ioctl_request", "addr"],
    "flock": ["valid_fd", "random_int"],
    "fsync": ["valid_fd"],
    "fdatasync": ["valid_fd"],
    "sync": [],
    "truncate": ["path", "size"],
    "ftruncate": ["valid_fd", "size"],
    "fallocate": ["valid_fd", "random_int", "offset", "size"],
    "sendfile": ["valid_fd", "valid_fd", "addr", "size"],
    "copy_file_range": ["valid_fd", "addr", "valid_fd", "addr", "size", "flags"],
    "splice": ["valid_fd", "addr", "valid_fd", "addr", "size", "splice_flags"],
    "vmsplice": ["valid_fd", "addr", "random_int", "flags"],
    "tee": ["valid_fd", "valid_fd", "size", "flags"],
    
    # === Directory Operations ===
    "getcwd": ["addr", "size"],
    "chdir": ["path"],
    "fchdir": ["valid_fd"],
    "chroot": ["path"],
    "mkdir": ["path", "mode"],
    "mkdirat": ["fd", "path", "mode"],
    "rmdir": ["path"],
    "getdents64": ["valid_fd", "addr", "size"],
    
    # === Link Operations ===
    "link": ["path", "path"],
    "linkat": ["fd", "path", "fd", "path", "flags"],
    "symlink": ["path", "path"],
    "symlinkat": ["path", "fd", "path"],
    "readlink": ["path", "addr", "size"],
    "readlinkat": ["fd", "path", "addr", "size"],
    "unlink": ["path"],
    "unlinkat": ["fd", "path", "flags"],
    "rename": ["path", "path"],
    "renameat": ["fd", "path", "fd", "path"],
    "renameat2": ["fd", "path", "fd", "path", "flags"],
    
    # === Permissions ===
    "chmod": ["path", "mode"],
    "fchmod": ["valid_fd", "mode"],
    "fchmodat": ["fd", "path", "mode", "flags"],
    "chown": ["path", "random_int", "random_int"],
    "fchown": ["valid_fd", "random_int", "random_int"],
    "fchownat": ["fd", "path", "random_int", "random_int", "flags"],
    "umask": ["mode"],
    
    # === Extended Attributes ===
    "setxattr": ["path", "addr", "addr", "size", "flags"],
    "lsetxattr": ["path", "addr", "addr", "size", "flags"],
    "fsetxattr": ["valid_fd", "addr", "addr", "size", "flags"],
    "getxattr": ["path", "addr", "addr", "size"],
    "lgetxattr": ["path", "addr", "addr", "size"],
    "fgetxattr": ["valid_fd", "addr", "addr", "size"],
    "listxattr": ["path", "addr", "size"],
    "llistxattr": ["path", "addr", "size"],
    "flistxattr": ["valid_fd", "addr", "size"],
    "removexattr": ["path", "addr"],
    "lremovexattr": ["path", "addr"],
    "fremovexattr": ["valid_fd", "addr"],
    
    # === Time Operations ===
    "utime": ["path", "addr"],
    "utimes": ["path", "addr"],
    "utimensat": ["fd", "path", "addr", "flags"],
    "nanosleep": ["addr", "addr"],
    "clock_gettime": ["clock_id", "addr"],
    "clock_settime": ["clock_id", "addr"],
    "clock_getres": ["clock_id", "addr"],
    "clock_nanosleep": ["clock_id", "flags", "addr", "addr"],
    "gettimeofday": ["addr", "addr"],
    "settimeofday": ["addr", "addr"],
    "times": ["addr"],
    
    # === Timers ===
    "timer_create": ["clock_id", "addr", "addr"],
    "timer_settime": ["random_int", "flags", "addr", "addr"],
    "timer_gettime": ["random_int", "addr"],
    "timer_getoverrun": ["random_int"],
    "timer_delete": ["random_int"],
    "timerfd_create": ["clock_id", "flags"],
    "timerfd_settime": ["valid_fd", "flags", "addr", "addr"],
    "timerfd_gettime": ["valid_fd", "addr"],
    
    # === Process Management ===
    "fork": [],
    "vfork": [],
    "clone": ["clone_flags", "addr", "addr", "addr", "addr"],
    "clone3": ["addr", "size"],
    "execve": ["path", "addr", "addr"],
    "execveat": ["fd", "path", "addr", "addr", "flags"],
    "exit": ["random_int"],
    "exit_group": ["random_int"],
    "wait4": ["pid", "addr", "wait_options", "addr"],
    "waitid": ["random_int", "pid", "addr", "wait_options"],
    
    # === Process Info & Credentials ... (no changes in these sections)
    "getpid": [],
    "getppid": [],
    "gettid": [],
    "getuid": [],
    "geteuid": [],
    "getgid": [],
    "getegid": [],
    "getpgrp": [],
    "getpgid": ["pid"],
    "getsid": ["pid"],
    "setsid": [],
    "setpgid": ["pid", "pid"],
    "setuid": ["random_int"],
    "setgid": ["random_int"],
    "setreuid": ["random_int", "random_int"],
    "setregid": ["random_int", "random_int"],
    "setresuid": ["random_int", "random_int", "random_int"],
    "setresgid": ["random_int", "random_int", "random_int"],
    "getresuid": ["addr", "addr", "addr"],
    "getresgid": ["addr", "addr", "addr"],
    "getgroups": ["random_int", "addr"],
    "setgroups": ["random_int", "addr"],
    "prctl": ["prctl_option", "random_int", "random_int", "random_int", "random_int"],
    "setpriority": ["random_int", "random_int", "random_int"],
    "getpriority": ["random_int", "random_int"],
    "nice": ["random_int"],
    "sched_yield": [],
    "sched_setscheduler": ["pid", "random_int", "addr"],
    "sched_getscheduler": ["pid"],
    "sched_setparam": ["pid", "addr"],
    "sched_getparam": ["pid", "addr"],
    "sched_setaffinity": ["pid", "size", "addr"],
    "sched_getaffinity": ["pid", "size", "addr"],
    "prlimit64": ["pid", "random_int", "addr", "addr"],
    
    # === Signals, Networking, I/O Multiplexing ... (no changes in these sections)
    "kill": ["pid", "signal"],
    "tkill": ["pid", "signal"],
    "tgkill": ["pid", "pid", "signal"],
    "rt_sigaction": ["signal", "addr", "addr", "size"],
    "rt_sigprocmask": ["random_int", "addr", "addr", "size"],
    "rt_sigsuspend": ["addr", "size"],
    "rt_sigqueueinfo": ["pid", "signal", "addr"],
    "rt_sigtimedwait": ["addr", "addr", "addr", "size"],
    "sigaltstack": ["addr", "addr"],
    "signalfd": ["valid_fd", "addr", "size"],
    "signalfd4": ["valid_fd", "addr", "size", "flags"],
    "socket": ["socket_domain", "socket_type", "socket_protocol"],
    "socketpair": ["socket_domain", "socket_type", "socket_protocol", "addr"],
    "connect": ["valid_fd", "addr", "size"],
    "bind": ["valid_fd", "addr", "size"],
    "listen": ["valid_fd", "random_int"],
    "accept": ["valid_fd", "addr", "addr"],
    "accept4": ["valid_fd", "addr", "addr", "flags"],
    "getsockname": ["valid_fd", "addr", "addr"],
    "getpeername": ["valid_fd", "addr", "addr"],
    "shutdown": ["valid_fd", "random_int"],
    "sendto": ["valid_fd", "addr", "size", "flags", "addr", "size"],
    "recvfrom": ["valid_fd", "addr", "size", "flags", "addr", "addr"],
    "sendmsg": ["valid_fd", "addr", "flags"],
    "recvmsg": ["valid_fd", "addr", "flags"],
    "sendmmsg": ["valid_fd", "addr", "random_int", "flags"],
    "recvmmsg": ["valid_fd", "addr", "random_int", "flags", "addr"],
    "setsockopt": ["valid_fd", "sockopt_level", "random_int", "addr", "size"],
    "getsockopt": ["valid_fd", "sockopt_level", "random_int", "addr", "addr"],
    "select": ["random_int", "addr", "addr", "addr", "addr"],
    "pselect6": ["random_int", "addr", "addr", "addr", "addr", "addr"],
    "poll": ["addr", "random_int", "random_int"],
    "ppoll": ["addr", "random_int", "addr", "addr"],
    "epoll_create": ["random_int"],
    "epoll_create1": ["flags"],
    "epoll_ctl": ["valid_fd", "random_int", "valid_fd", "addr"],
    "epoll_wait": ["valid_fd", "addr", "random_int", "random_int"],
    "epoll_pwait": ["valid_fd", "addr", "random_int", "random_int", "addr"],
    "eventfd": ["random_int"],
    "eventfd2": ["random_int", "flags"],
    "inotify_init": [],
    "inotify_init1": ["flags"],
    "inotify_add_watch": ["valid_fd", "path", "random_int"],
    "inotify_rm_watch": ["valid_fd", "random_int"],
    "fanotify_init": ["flags", "flags"],
    "fanotify_mark": ["valid_fd", "flags", "random_int", "valid_fd", "path"],
    "futex": ["addr", "random_int", "random_int", "addr", "addr", "random_int"],
    "set_robust_list": ["addr", "size"],
    "get_robust_list": ["pid", "addr", "addr"],
    "set_tid_address": ["addr"],
    
    # === System V IPC === (no changes)
    "shmget": ["random_int", "size", "flags"],
    "shmat": ["random_int", "addr", "flags"],
    "shmdt": ["addr"],
    "shmctl": ["random_int", "random_int", "addr"],
    "semget": ["random_int", "random_int", "flags"],
    "semop": ["random_int", "addr", "size"],
    "semctl": ["random_int", "random_int", "random_int", "addr"],
    "msgget": ["random_int", "flags"],
    "msgsnd": ["random_int", "addr", "size", "flags"],
    "msgrcv": ["random_int", "addr", "size", "random_int", "flags"],
    "msgctl": ["random_int", "random_int", "addr"],

    # === Special Files ===
    "mknod": ["path", "mode", "random_int"],
    "mknodat": ["fd", "path", "mode", "random_int"],
    
    # === Advanced/Kernel ... (no changes)
    "ptrace": ["ptrace_req_cve", "pid", "addr", "addr"],
    "bpf": ["bpf_cmd", "addr", "size"],
    "keyctl": ["keyctl_cmd", "random_int", "random_int", "random_int", "random_int"],
    "userfaultfd": ["userfaultfd_flags"],
    "seccomp": ["seccomp_flags", "flags", "addr"],
    "perf_event_open": ["addr", "pid", "cpu", "valid_fd", "flags"],
    "io_uring_setup": ["random_int", "addr"],
    "io_uring_enter": ["valid_fd", "random_int", "random_int", "flags", "addr", "size"],
    "io_uring_register": ["valid_fd", "random_int", "addr", "random_int"],
    
    # === Namespaces ===
    "unshare": ["flags"],
    "setns": ["valid_fd", "flags"],
    "kcmp": ["pid", "pid", "random_int", "random_int", "random_int"],
    "pidfd_open": ["pid", "flags"],
    "pidfd_send_signal": ["valid_fd", "signal", "addr", "flags"],
    "pidfd_getfd": ["valid_fd", "valid_fd", "flags"],
    
    # === Mount ===
    "mount": ["path", "path", "path", "mount_flags", "addr"],
    "umount2": ["path", "flags"],
    "pivot_root": ["path", "path"],
    
    # === Modules ===
    "init_module": ["addr", "size", "addr"],
    "finit_module": ["valid_fd", "addr", "flags"],
    "delete_module": ["addr", "flags"],
    
    # === Capabilities ===
    "capget": ["addr", "addr"],
    "capset": ["addr", "addr"],
    
    # === System Info ===
    "uname": ["addr"],
    "sysinfo": ["addr"],
    "syslog": ["random_int", "addr", "size"],
    "getcpu": ["addr", "addr", "addr"],
    "getrandom": ["addr", "size", "flags"],
    
    # === Misc ===
    "ioperm": ["random_int", "random_int", "random_int"],
    "iopl": ["random_int"],
    "quotactl": ["random_int", "path", "random_int", "addr"],
    "lookup_dcookie": ["random_int", "addr", "size"],
    "name_to_handle_at": ["fd", "path", "addr", "addr", "flags"],
    "open_by_handle_at": ["fd", "addr", "flags"],
    "reboot": ["random_int", "random_int", "random_int", "addr"],
}